### ISSUE TITLE
Add option for users to change wallpaper at the time they want

### ISSUE THREAD

**Issue by sam09** [Spockuto/Wallpaper-of-the-day#1]

**Comment by Spockuto** [comment]
Added Configuration.
configure.sh

**Comment by sam09** [comment]
<pre> Enter the hour 0-23(* for every)
0
Enter the minute 0-59(* for every)
0
0 0 * * * ruby /home/skidm/ThePaperWall/Scripts/Wallpaper.rb
tempfile: No such file or directory
rm: cannot remove ‘tempfile’: No such file or directory
Your Wallpaper will be updated at 0:0
Be sure to have your Laptop On and Connected to the network
</pre>

@Spockuto check out the error

**Comment by Spockuto** [comment]
I commented the part where its created . My bad.
Its fixed now.

**Comment by sam09** [comment]
@Spockuto  Good job
